Feat mypage 코드 정리 및 삭제
Nito-90z/Nito-Frontend pull request #21
Opened 2024-10-28 06:50 UTC by yungiy

마이페이지에서 유저 조회기능 빼고 나머지 모두 삭제 했습니다.

2024-10-28 13:37 UTC, GangHub1970 requested changes
코멘트 달았습니다!
1. UI 적으로는 마이페이지 "니토 사용법", "개인정보처리방침"같은 항목 옆에 있는 버튼이 너무 중간으로 밀려있는 느낌이 드는것 같아요.
2. 가격할인 설정 바텀 시트는 상단에 테두리라도 있는게 좀 더 좋을것 같은데 어떠세요?
3. 마지막으로 네브바가 없는 페이지에는 뒤로가기 버튼이 있으면 더 좋을 것 같은데 어떻게 생각하시는지요????

2024-10-28 13:37 UTC, GangHub1970 commented on src/components/header/SelectHeader.tsx
이 컴포넌트 찜한 목록 페이지에서도 사용하고 있었는데 거기서는 onCLick이 필요합니다!
옵셔널로 변경하고 onClick 함수를 props로 받을 수 있게 수정해주세요.

2024-10-28 13:37 UTC, GangHub1970 commented on src/app/(withoutNavBar)/mypage/page.tsx
> +        {/* <SocialLogin /> */}
이 주석은 소셜 로그인 기능을 구현하지 않아서 주석 처리 하신건가요?

2024-10-28 15:43 UTC, yungiy commented on src/components/header/SelectHeader.tsx
수정했습니다~

2024-10-28 15:44 UTC, yungiy commented on src/app/(withoutNavBar)/mypage/page.tsx
> +        {/* <SocialLogin /> */}
네네 근데 만약 빌드나 배포과정에서 오류난다면 지워도 될거같습니다.

2024-10-28 15:46 UTC, yungiy commented
1번이 그 mypage에서 말씀하시는건가용 아니면 헤더에서 말씀하시는건가요?
그 외에 바텀시트들에게 테두리 먹였고 네브바 없는 페이지들은 뒤로가기 기능 추가해놨습니다.

2024-10-28 17:47 UTC, GangHub1970 commented
<img width="429" alt="스크린샷 2024-10-29 오전 2 45 00" src="https://github.com/user-attachments/assets/dfe961d5-c846-47c2-8f28-da1546f0a942">

파란 동그라미 부분을 옆으로 살짝 보내면 좋을 것 같아요. 지금은 아이콘 크기보다 버튼이 옆으로 너무 커서 이런것 같습니다!

2024-10-29 05:54 UTC, GangHub1970 approved these changes
수고하셨습니다!!

2024-10-29 05:55 UTC, merged